runtime: nodejs16 
network:
  session_affinity: true

instance_class: F2

env_variables: 
  BUCKET_NAME: "healthy-fuze"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto